POST http://localhost:8888/accounts
Content-Type: application/json

{
  "id": "TEST",
  "name": "TEST_NAME",
  "password": "password"
}

<> 2020-03-06T110759.200.json

###
POST http://localhost:8888/login
Content-Type: application/json

{
  "id": "TEST",
  "password": "password"
}

<> 2020-03-06T111312.200.json
<> 2020-03-06T111149.401.json
<> 2020-03-06T110933.500.json

###

POST http://localhost:8888/naming
Content-Type: application/json

{
  "name": "TEST",
  "description": "password",
  "account": {
    "idx": 1,
    "id": "TEST",
    "name": "TEST_NAME"
  }
}

###

GET http://localhost:8888/naming/pass
Content-Type: application/json

###