POST http://192.168.1.224:8123/accounts
Content-Type: application/json

{
  "id": "",
  "name": "Admin",
  "password": ""
}

<> 2020-03-06T110759.200.json

###
POST http://127.0.0.1:8123/login
Content-Type: application/json

{
  "id": "admin",
  "password": "admin"
}

###
POST http://localhost:8123/naming
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuYW1pbmdDZW50ZXJKV1QiLCJpc3MiOiJuYW1pbmdDZW50ZXIiLCJhdXRob3JpdGllcyI6WyJST0xFX0dVRVNUIl0sImlkIjoiYWRtaW4iLCJpYXQiOjE2MDM0MzQ2MzYsImV4cCI6MTYwMzQzNTIzNn0.0l447JjHgTVFwLflZ9OeWvdUkXc-Ejjh5TwMXCkkGUTV1DllLQy-yBzL3gkAftztjRjbP-RPCI5U5U_ISt4xSw

{
  "name": "TEST",
  "description": "password",
  "account": {
    "idx": 1,
    "id": "TEST",
    "name": "TEST_NAME"
  }
}

###

GET http://localhost:8888/naming/pass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuYW1pbmdDZW50ZXJKV1QiLCJpc3MiOiJuYW1pbmdDZW50ZXIiLCJhdXRob3JpdGllcyI6WyJST0xFX0dVRVNUIl0sImlkIjoiYWRtaW4iLCJpYXQiOjE2MDM0MzQ2MzYsImV4cCI6MTYwMzQzNTIzNn0.0l447JjHgTVFwLflZ9OeWvdUkXc-Ejjh5TwMXCkkGUTV1DllLQy-yBzL3gkAftztjRjbP-RPCI5U5U_ISt4xSw

###