# --spring.profiles.active=develop (program argument)
spring:
  profiles: develop

#  http://localhost:8888/h2-console
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:namingcenter
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: true
        globally_quoted_identifiers: true
        format_sql: true

server:
  port: 8888